import { Layouts } from "react-grid-layout";

export const layouts: Record<string, Layouts> = {
  all: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 2, w: 1, h: 2 },
      { i: "weather", x: 1, y: 2, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 2, w: 1, h: 2 },
      { i: "quote", x: 3, y: 0, w: 1, h: 4 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },
      { i: "company", x: 2, y: 6, w: 2, h: 2 },
      { i: "contact", x: 0, y: 6, w: 2, h: 2 },
      { i: "computer", x: 2, y: 4, w: 1, h: 2 },
      { i: "notter", x: 3, y: 4, w: 1, h: 2 },
    ],
    // Same as lg
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "animatedEmoji", x: 2, y: 0, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 2, w: 1, h: 2 },
      { i: "weather", x: 1, y: 2, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 2, w: 1, h: 2 },
      { i: "quote", x: 3, y: 0, w: 1, h: 4 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },
      { i: "company", x: 2, y: 6, w: 2, h: 2 },
      { i: "contact", x: 0, y: 6, w: 2, h: 2 },
      { i: "computer", x: 2, y: 4, w: 1, h: 2 },
      { i: "notter", x: 3, y: 4, w: 1, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 0, y: 2, w: 1, h: 1 },
      { i: "computer", x: 1, y: 4, w: 1, h: 2 },
      { i: "cardStack", x: 0, y: 6, w: 1, h: 2 },
      { i: "contact", x: 0, y: 10, w: 2, h: 2 },
      { i: "animatedEmoji", x: 0, y: 4, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "quote", x: 1, y: 6, w: 1, h: 4 },
      { i: "notter", x: 0, y: 8, w: 1, h: 2 },
      { i: "mapComponent", x: 1, y: 2, w: 1, h: 2 },
      { i: "company", x: 0, y: 12, w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 0, y: 2, w: 1, h: 1 },
      { i: "computer", x: 0, y: 6, w: 1, h: 1 },
      { i: "animatedEmoji", x: 0, y: 4, w: 2, h: 2 },
      { i: "cardStack", x: 0, y: 7, w: 2, h: 2 },
      { i: "contact", x: 0, y: 12, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "quote", x: 0, y: 9, w: 2, h: 3 },
      { i: "notter", x: 1, y: 6, w: 1, h: 1 },
      { i: "mapComponent", x: 1, y: 2, w: 1, h: 2 },
      { i: "company", x: 0, y: 14, w: 2, h: 1 },
    ],
    // Same as xs
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 0, y: 2, w: 1, h: 1 },
      { i: "computer", x: 0, y: 6, w: 1, h: 1 },
      { i: "animatedEmoji", x: 0, y: 4, w: 2, h: 2 },
      { i: "cardStack", x: 0, y: 7, w: 2, h: 2 },
      { i: "contact", x: 0, y: 12, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "quote", x: 0, y: 9, w: 2, h: 3 },
      { i: "notter", x: 1, y: 6, w: 1, h: 1 },
      { i: "mapComponent", x: 1, y: 2, w: 1, h: 2 },
      { i: "company", x: 0, y: 14, w: 2, h: 1 },
    ],
  },

  about: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "cardStack", x: 2, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 1, y: 2, w: 1, h: 2 },
      { i: "computer", x: 0, y: 2, w: 1, h: 2 },
      { i: "weather", x: 3, y: 2, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 2, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 4, w: 1, h: 2 },
      { i: "quote", x: 3, y: 4, w: 1, h: 4 },
      { i: "contact", x: 0, y: 4, w: 2, h: 2 },
      { i: "company", x: 1, y: 6, w: 2, h: 2 },
      { i: "notter", x: 0, y: 6, w: 1, h: 2 },
    ],
    // Same as large
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "cardStack", x: 2, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 1, y: 2, w: 1, h: 2 },
      { i: "computer", x: 0, y: 2, w: 1, h: 2 },
      { i: "weather", x: 3, y: 2, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 2, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 4, w: 1, h: 2 },
      { i: "quote", x: 3, y: 4, w: 1, h: 4 },
      { i: "contact", x: 0, y: 4, w: 2, h: 2 },
      { i: "company", x: 1, y: 6, w: 2, h: 2 },
      { i: "notter", x: 0, y: 6, w: 1, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 1, y: 4, w: 1, h: 2 },
      { i: "iconCloud", x: 1, y: 2, w: 1, h: 1 },
      { i: "contact", x: 0, y: 10, w: 2, h: 2 },
      { i: "mapComponent", x: 0, y: 2, w: 1, h: 2 },
      { i: "computer", x: 1, y: 2, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 1, h: 2 },
      { i: "animatedEmoji", x: 0, y: 6, w: 1, h: 2 },
      { i: "quote", x: 1, y: 6, w: 1, h: 4 },
      { i: "notter", x: 0, y: 8, w: 1, h: 2 },
      { i: "company", x: 0, y: 12, w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 0, y: 8, w: 1, h: 1 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "contact", x: 0, y: 11, w: 2, h: 2 },
      { i: "mapComponent", x: 1, y: 2, w: 1, h: 2 },
      { i: "computer", x: 0, y: 2, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },
      { i: "animatedEmoji", x: 0, y: 6, w: 2, h: 2 },
      { i: "quote", x: 0, y: 9, w: 2, h: 2 },
      { i: "notter", x: 1, y: 8, w: 1, h: 1 },
      { i: "company", x: 0, y: 13, w: 2, h: 1 },
    ],
    // Same as xs
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "weather", x: 0, y: 8, w: 1, h: 1 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "contact", x: 0, y: 11, w: 2, h: 2 },
      { i: "mapComponent", x: 1, y: 2, w: 1, h: 2 },
      { i: "computer", x: 0, y: 2, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },
      { i: "animatedEmoji", x: 0, y: 6, w: 2, h: 2 },
      { i: "quote", x: 0, y: 9, w: 2, h: 2 },
      { i: "notter", x: 1, y: 8, w: 1, h: 1 },
      { i: "company", x: 0, y: 13, w: 2, h: 1 },
    ],
  },
};

export const selectedCard: Record<string, Record<string, boolean>> = {
  all: {
    avatar: true,
    weather: true,
    cardStack: true,
    animatedEmoji: true,
    mapComponent: true,
    iconCloud: true,
    quote: true,
    contact: true,
    computer: true,
    company: true,
    notter: true,
  },
  about: {
    avatar: true,
    weather: false,
    cardStack: true,
    animatedEmoji: false,
    mapComponent: true,
    iconCloud: true,
    quote: false,
    contact: false,
    computer: true,
    company: false,
    notter: false,
  }
};
